<?php
   $collection = $this->getDeveloperCollection();
   ?>
<div class="col-md-12">

   <div class="ves-inner padding-bottom0  block">
      <div class="row row-level-1  ">
         <div class="row-inner clearfix a-center">
            <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
               <div class="col-inner ">
                  <div class="ves-container   ">
				     <?php foreach ($collection as $key => $data): ?>
   <?php //print_r($data->getData());
      /*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
      $store = $storeManager->getStore();
      $mediaUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);*/	
      $team_id = $data->getTeamName()
      ?>
                     <div class=" col-lg-3 col-md-3 col-sm-3 col-xs-12  ">
                        <div class="col-inner ">
                           <div>
                              <div class="ves-widget widget-images block no-effect  ">
                                 <div class="widget-inner block-content clearfix">
                                    <div class="image-item">
                                       <span class="img-animation"><img style="width:130px;" src="<?php echo $data->getDeveloperImage(); ?>" class="img-responsive  center-block img-circle" alt="Image"></span>
                                       <div class="image-description ">
                                          <h4 class="text-center" style="margin-bottom:5px;"><?php echo $data->getDeveloperName(); ?></h4>
                                          <p class="text-center marging0"><?php echo $data->getEMail(); ?></p>
                                          <p class="text-center"><?php echo $data->getMobileNo(); ?></p>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <?php endforeach; ?>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>