<?php
   $collection = $this->getTeamCollection();
   ?>
<div class="col-md-12">

   <div class="ves-inner padding-bottom0  block">
      <div class="row row-level-1  ">
         <div class="row-inner clearfix a-center">
            <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
               <div class="col-inner ">
                  <div class="ves-container   ">
					<?php 	
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
						$storeUrl = $storeManager->getStore()->getBaseUrl(); 
					?>
                    <?php foreach ($collection as $key => $data): ?>
					 <div class=" col-lg-4 col-md-4 col-sm-4 col-xs-12  ">
                        <div class="col-inner ">
                           <div>
                              <div class="ves-widget widget-images block no-effect  ">
                                 <div class="widget-inner block-content clearfix">
                                    <div class="image-item">
                                       <span class="img-animation"><a href="<?php echo $storeUrl.'grid/index/listdata/team_id/'.$data->getTeamId(); ?>"><img  src="<?php echo $data->getTeamImage(); ?>" class="img-responsive  center-block " alt="Image"></a></span>
                                       <div class="image-description ">
                                          <h4 class="text-center" ><?php echo $data->getTeamName();  ?></h4>
                                          <p class="text-center marging0"><?php echo $data->getTeamDescription(); ?></p>
									   </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                    <?php endforeach; ?>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
