<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$enable_flag_template = $ves->getHeaderCfg("language_switcher_settings/language_switcher_template");
if($enable_flag_template == "Magento_Store::switch/flags.phtml" || $enable_flag_template == '1'){
    $enable_flag_template = true;
} else {
    $enable_flag_template = false;
}
$enable_flag_label = $ves->getHeaderCfg("language_switcher_settings/language_label");
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
$id .= time() . uniqid();
?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label hidden"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>    
    <span class="switcher-title hidden"><?php /* @escapeNotVerified */ echo __('Language : ') ?></span>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if($enable_flag_template) { ?>
                <span class="flag-icon flag-icon-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>"></span> 
                <?php } ?>
                <?php if($enable_flag_label) { ?>
                <span><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
                <?php } ?>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?php if($enable_flag_label) { ?>
                            <?php echo $block->escapeHtml($_lang->getName()) ?>
                            <?php } ?>
                            <?php if($enable_flag_template) { ?>
                            <span class="flag-icon flag-icon-<?php echo $_lang->getCode() ?>"></span> <?php echo $block->escapeHtml($_lang->getName()) ?>
                            <?php } ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
